sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-node
  - secure: Ai+nCI55i/g+UMJgWfMuHER8ZhE12AAevRKZu4DHU4Xagor8QVzOAmxtvVlQHrivorUJdlM0IUK3lbc6HL7PiiaRhnhe+cskVOpMJxYoE+PsoVxqfBWRj7W8O0yKSyDHRnGR4OlYc47vYj/VjD/g3sIoEpJB86IczQGCBa39tsZ5X3+oeyxEhfrptbAA46adnRDpReY3lrGFkiRYnveZU0aMVy87NuVkH5ndZrIIBZBe4qSxb9rOZEiDJIdPWsSKtHU4AOOWk5YUwP4chNiJkcxyq6YUL68xbM6neMzdmayTtWmrjim9GCft1azZmo5sOZvaG4Xz9LojTUNrNk3Y+ffhR4b7MXyxJzX7HfzGQ5JT+TmoOfuzbpEvXypkAEqcvgCUU9wplpUmhirhIfVW9Y0ZU/oeWV2lQLiNoEdAA/rTyNBGdbu3pYTSkR5pIzDkMTQRQEBkiwtPCuJIyfCjYtSdCRHWC2wd8AfKqbvlhwmZmYxRNCFof8VtGNc9e89K6GgpA3M/RBtXNuebTsDgA0BKWSxE5Co3FFdQLDbMFWrZgrHidecxj6C+jPpO4vgU3/ljeWhBFNfnrw7hXu4L5CkDaJNPhgYRV9GoYHF3K77mG6oCmGndGSZSAybFpIsThlEn44mc8xtJdkouoJiG8/sn3lcimZvrmrJGXpwWw28=
  - secure: JpfVR37Ay8nVz1+/SJx9SY9XxHLIRQW8prIAboswKJbuRKKzgyXhUa9kJEZS1ieWv3kokzN5HFKd8ldArOS4yCDpRvKjWixcxbDWl2rVBXcwCwGjnaDM40V3hp0jfo85VHNjj/zu23o0AJbUyF+ZMzAocXP9UVJ6ntQ+IgdLY0xWgnpt4v3cMqG6s/iihQ2NYpLPpFKzCVZTfFzQSLweboHtMXws6gbvG+0QmAXajhUQbl8+tuXU2uzEA/qYHCkTaGeNI+2IjcgazwxT0hm6D2/ScF4j6SqwnSLdPF5XFnDjheWUKtXqgx8J0s6X/2YTOwOMCVxZHscZGgnxwS7ZL90ZidTBG8GIInBr6rdZTrJG/JZ5w7eKFtUg4yfk+yGu/FPUVdYsB4K31Pghw6VJSuma18QL3zCBduD3RX7ZPWUuOiB7WxsUpBrIqXw+CTvjnei+6J+Hy36M3ax6JyoHP82ZYRGQ3zNVjX/QB/x0jQ4/jlblaKtjzWm9n4sl1HNZW1a8HKYmUXeIxU/OPD+uz93cLZ0uQc1+XC4d5X3z/UwmK3ol48plp+phpU/G9LbbL2+5aVP0APCCBY/CwDmkTPUgDgWyxcNhdnOYbJHtqebZr2n9J0W1lswdG1MEqrkmx5Q5mzHlDjvDTFt4gINZCDPc0oK9UMwDOgLpAOkE/DU=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
