sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-node
  - secure: n1qnlzPnWoGmSjb6KQ8JnrePiQiZT7H7pPjjKq4LSCUoQQpsia6AB/IiL2PM6ugTMWDksjntr+L7nNWAoOCoSfUNfgXbyq3jdYC45QmytaVIqhqhqt7GQFp1Lw6MK8sLlkv8KCscnf499L+rHBIv7HaBGKoPZAh46lHg49+7qkwKVRxC0FOkPei+CwFuQzbfJH/mVEZgzykKqox+SqDVbKMKFfEgdLO/f1QQyn0Z2q1eSIklHncRk8jmChxu3nZ7aVlOm5WFZuQYyaieHdioKVWBW6RcBUAG+ZEVV7htCEFlgFlLFIlJX2KYCrMkW5gIKEVFHNQQ30MS76jk5sXsL9aWQZlU+88t1R75retHfsFintBbaufCQLP9Xxft6n7QpEu7iOZhLJORxxUEaPjoiLFjjaBG/i2BYL/24PnZQQxKTiVFb7kX/7fVOlMLREQrXy6t78LzPSemoF5EamoPJ5nrwZIB3V06lqqDSTnD5ZpnL6rdGEQkbYIcEezWoaQwM4mHpxr27sNCts+aVMBQHP9rJppjLgCSQfoktL4gReauwpk2YLgKiXLzF6I2DzK+yY8QAorWZXB2eAPYFCcY0/eLAB4cjkPidNFnbd3jH6fVwrgGgK5RhL1s9NZHo7RI/oY9H1+8w4twAuoM6/pE3xflXkduB87kVhowGpUybdk=
  - secure: gOysNkD9/XuepUoUxEklwp6yjjJf18CMf0u/s/lSomO3S3vJYUQE9lPv3Kixbs8odYMmNo8+dAEs6mCx0JIkoJXARi0CeZaEx0vxZaJH5jCgBCJxSo7eCtwPob/ysHEKERKmsmTvLkNI2Y6MvvaPU5MS5US3KEENxzD7Nghy9hgX/bQGItsuLPRmX7KYhZgcGvzWnXhYVO3ND+06+Wz/YB/b11YSsoiWz3jww0RLiWzRASoNh501EkyfTL+D3kIpl5+cqCl/dnpT5I0Did0rnrnbTDFB2TUa/cW9jdbuy/dEkZzsm848ygAbRGHbetHKJ1mmCVMjlUiWmsXntlrhw2wmlO+xbR5XmfXfrNkBYtt0O3KJkf5NYgB3uNpufy/CQQd13X/1Jum3kNhL6mN9olI3l1jZuRVBOfuE2YOAFwwIx0ra2S6T0Kpgy85iJW2mXoKlhWXG91G6OJdDF2zeTzqLDcqw6xLWF8F88pRJdnMKWPqWC7yg6E00Lur4lf29+8/JSXPsHO7xClJKXT1lDy4CXKb8PZefMsw/PntODVB3EG8Hm03/dYq+N2zPTE/jZAc5gAt29fxrivJ1PIRW1002HajMUTLdNpRCosbI6b9wg475TCxN4SiPe/TJZs5WZU6ntVzGTeD1RXqLqzUfGRnXsdsBWb7vYLmylwQ+lpA=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
