sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-node
  - secure: 9Jyh/kct0vHEMkBvx1VimAn43798pj7TM4uj9240h5L9nCu/NzCaYoYAyohOCue8hP10Nou+bVrzPBYZvU22kvYBz/QV4S2DgWXUyXlRhgaT4EmH8/2qn9o+ovcdmYN6zf2eHwo1mzwdPpmRbe9t1xj7tW67WPJkTofyp0/PfH460Q0f4rTZdh7OuOQyy3lsJF4i8ox2KTalUQwjV31soQ096aXrzd1l0x1KDRpPqbZSSfj5T2flBOOcKF5ZF/qgQGc57gxsetEEswa6VZRZe23OZoCOI5iIk1jBEH0IGirbTCHLYatxAwUBILHncDMteIhTpNhkuoTKWlMnlUbPOsd4YZrx3cdnXwX2a1T/6bdc+k4kEYb+WgMT8VLpxWBhJFL3KnL6curwrBwg2dXg99TUzjG2hj7HNlVMA3zjv7S3z4WLp14xKzdjuHZGqVVrWiM8HorteR3iN7AjSg5Hpv7720Ey7Ogh/K/aL2LAyhqDzz9x01X+j5fCE1KVUhL7ANa8jZZxrFjifBKYdqcdPStqLNbmXX6kBjjW5QxQeB9bVIPX2/w16gEF4d4HvG7wL5gimYRxjGcRD2EfomIpCnw8oXFS/5C4U5GLEA3ALOjjlNIjXoGwjiEJDWtWcTxf8fiJrBWi2yCfXhLZ3hwvT7p1DlSSNZR+Y3tqrHOyFow=
  - secure: yK4B+Vo2nn8XEN5pCq/NwepOEtjPWfHrL4EcUKKSZoKP/6vHmjoSDy4HbpmuiygvD8NzaDU77ECuNUpByJzWrMBXeV5EHxUl/avp3fB16TF0rh8fVjeQDMkOYPm+TF2gC9tEvgQdAaRox3xuDOUX5PXmnY86f4VT9uQxiYb7wYSRoe6A61/ZcSJc/LuGPvs6FbFor7RkWPtr0C9xJyK0JxFMKmNFVmh7QRdGUUZxzQy1mOHTMagHUPsDzl/bHGJ7hs9pZHz70B35OYimr9CSOgKl3O2s4VmX8ZJyyZb7cN9nZ6IksgrtJFFp4BamD+pKPO+pgrDDKKis9KHTLsYG03TlqF0Lb5ZD2t90gkfvZFSaOe0J4yZXQ7+csRztbQQNA73MTsTwIxZI2D8C2ZD3RgRci4rerVnenyzWktiHnr/NTNhvS6+HtVuZ6A++y0Z3cNJsDwh5uu6s+jl0+m0QZ7siy+tpiWfRDKpXsfyYDt3Q2ZVDY3/kI6gzXviD3y4HkAWWPpNMiozXL5st5bTvbBHpgaiVwLo0qIWVmojOnCr4XIOFp3D5XSGYAr08jDyTSrG8Av4evZjgtVVq+rz1dbGkq5JwYqBLQmlWZYXQwoGrWhDmnBbbqo8CxH5tz85LHQUbY+SO0tc56RXXtWqEsLdPitc9CjP/ek/LeG8G14w=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
