name: Build VNCChromeNode

on:
  push:
    branches:
      - fixv4
    paths:
      # '*' matches any character except '/'
      - 'image/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: fixv4
    - name: Docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets. DOCKER_HUB_USERNAME }} 
        DOCKER_HUB_PASSWORD: ${{ secrets. DOCKER_HUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin
    - name: Build & Push Docker Image
      run: |
        cd image
        IMAGE_NAME=ringcentral/vnc-chrome-node
        IMAGE_TAG=v4
        GH_DOCKER_PKG_IMAGE_NAME=docker.pkg.github.com/ringcentral-docker/vnc-chrome-node/vnc-chrome-node
        BASE_VERSION="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
        NODE_VERSION="node$(awk -F '[=]'  '/ARG/ {print $2}' Dockerfile)"
        docker build --tag ${IMAGE_NAME} --file Dockerfile .
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${BASE_VERSION}-${NODE_VERSION}"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_TAG}"
        
        docker push "${IMAGE_NAME}:${BASE_VERSION}-${NODE_VERSION}"
        docker push "${IMAGE_NAME}:${IMAGE_TAG}"

        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}-${NODE_VERSION}"
        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${IMAGE_TAG}"

        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${BASE_VERSION}-${NODE_VERSION}"
        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${IMAGE_TAG}"